baseURL = 'https://picoder3141.github.io/'
languageCode = 'en-us'
title = 'PiExplorer'
theme = 'ananke_fork'
sectionPagesMenu = 'main'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]']]
          inline = [['$', '$']]
[params]
  math = true
  toc = true
