baseURL = 'https://picoder3141.github.io/'
languageCode = 'en-us'
title = 'PiExplorer'
theme = 'ananke'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]']]
          inline = [['$', '$']]
[params]
  math = true
